### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by mbojan** [sckott/oai#10]
https://www.openarchives.org/OAI/openarchivesprotocol.html#ErrorConditions

I think currently only HTTP errors are handled through `httr::stop_for_status` in `while_oai`.

**Comment by mbojan** [comment]
Ah, there is `handle_errors`...
Sorry!

**Comment by mbojan** [comment]
Actually, I think this could be improved:

- `handle_errors` takes XML as a character vector, parses it with `read_xml` to check for `<error>` tag. The XML is then parsed again outside of `handle_errors` in both `get_record` and `while_oai`. This seems inefficient.
- More serious problem. Sometimes the XML can be malformed. I encountered it when working with my OAI-PMH source: some records contain UTF-8 characters that are unacceptable by XML and `xml2::read_xml` trips over (it is actually `libxml` that throws an error). I think requesting raw results could (optionally?) work with text without XML parsing.

**Comment by sckott** [comment]
That sounds good, the change to `handle_errors()`

**Comment by mbojan** [comment]
Closing because `handle_errors` has been updated. Discussion of other ideas moved largely to #17
