### ISSUE TITLE
Calling `list_records` with known resumption `token` makes a bad URL

### ISSUE THREAD

**Issue by mbojan** [sckott/oai#18]
See the request made by
```r
list_records(token="foo", config=httr::verbose())
```
The request should contain the parameter `resumptionToken` (not `token`) and no other parameters (without `metadataPrefix`). So it should be:

```r
r <- httr::GET("http://oai.datacite.org/oai?verb=ListRecords&resumptionToken=foo",
     config=httr::verbose())
httr::content(r, "text")   
```
which properly includes `badResumptionToken` error code for `resumptionToken=foo`

Perhaps also `list_records` when given a `token` should compose the URL without any other arguments whatever user supplied or give errors immediately, for example:

```r
list_records(from="2015-09-01T", until="2015-09-01T", 
    token="foo", config=httr::verbose())
```
should skip not only the prefix (which puts some default), but also `from` and `until` and so on

**Comment by sckott** [comment]
thanks - pushed some fixes, needed same in `list_identifiers` as well

**Comment by mbojan** [comment]
Looks fine to me.
